# Creación y Manipulación de DataFrames

## Creación de un DataFrame

In [1]:
### Importamos nuestro pandas
import pandas as pd

## Inicializacion de un dataframe

* Imagenemos que tenemos los siguientes datos
* Nota:
  - Cada elemento de un data frame es una serie.
  - De esta manera solo lista los valores `paises = pd.DataFrame(datos)`.
  - Es decir no tiene contexto.

In [4]:
nombre_paises = ["China", "India", "Estados Unidos", "Indonesia", "Paskitán", "Brasil",
                "Nigeria", "Bangladesh", "Rusia", "México"]

encabezado = ["poblacion", "porcentaje"]

datos = [[1439, 18.47], 
         [1380 ,17.70], 
         [331, 4.25], 
         [273, 3.51], 
         [220, 2.83],
         [212, 2.73], 
         [206, 2.64], 
         [164, 2.11], 
         [145, 1.87], 
         [128, 1.65]]

### Creamos el data frame de esta forma le pone más contexto
paises = pd.DataFrame(datos, index=nombre_paises, columns=encabezado)
paises

                poblacion  porcentaje
China                1439       18.47
India                1380       17.70
Estados Unidos        331        4.25
Indonesia             273        3.51
Paskitán              220        2.83
Brasil                212        2.73
Nigeria               206        2.64
Bangladesh            164        2.11
Rusia                 145        1.87
México                128        1.65

### Transformar un diccionario a DataFrame

In [5]:
### Imaginemos que tenemos este diccionario

diccionario = {
    "China": [1439, 18.47],
    "India": [1380, 17.70],
    "Estados Unidos": [331, 4.25],
    "Indonesia": [273, 3.51],
    "Paskitán": [220, 2.83],
    "Brasil": [212, 2.73],
    "Nigeria": [206, 2.64],
    "Bangladesh": [164, 2.11],
    "Rusia": [145, 1.87],
    "México": [128, 1.65]
}

# Esto hará que este transpuesto, tenemos que establecer los indices
# ya que por default empezarán con 0 o 1.
paises = pd.DataFrame(diccionario, index=encabezado)
print("Normal: \n", paises)

### transponer el dataframe
paises = paises.transpose()
print("Transpuesto: \n", paises)

Normal:
               China   India  Estados Unidos  Indonesia  Paskitán  Brasil  \
poblacion   1439.00  1380.0          331.00     273.00    220.00  212.00
porcentaje    18.47    17.7            4.25       3.51      2.83    2.73

            Nigeria  Bangladesh   Rusia  México
poblacion    206.00      164.00  145.00  128.00
porcentaje     2.64        2.11    1.87    1.65
Transpuesto:
                 poblacion  porcentaje
China              1439.0       18.47
India              1380.0       17.70
Estados Unidos      331.0        4.25
Indonesia           273.0        3.51
Paskitán            220.0        2.83
Brasil              212.0        2.73
Nigeria             206.0        2.64
Bangladesh          164.0        2.11
Rusia               145.0        1.87
México              128.0        1.65

## Métodos de un DataFrame

In [6]:
### Imprimir el tipo de datos de nuestro dataFrame
paises.dtypes

poblacion     float64
porcentaje    float64
dtype: object

In [7]:
### Accedemos la data
print("Valores: \n", paises.values)
print("Size: ", paises.size)

Valores:
 [[1439.     18.47]
 [1380.     17.7 ]
 [ 331.      4.25]
 [ 273.      3.51]
 [ 220.      2.83]
 [ 212.      2.73]
 [ 206.      2.64]
 [ 164.      2.11]
 [ 145.      1.87]
 [ 128.      1.65]]
Size:  20

In [8]:
print("Indices: \n", paises.index)
print("Columnas: ", paises.columns)

Indices:
 Index(['China', 'India', 'Estados Unidos', 'Indonesia', 'Paskitán', 'Brasil',
       'Nigeria', 'Bangladesh', 'Rusia', 'México'],
      dtype='object')
Columnas:  Index(['poblacion', 'porcentaje'], dtype='object')

## Acceder a un elemento del DataFrame

* Podemos acceder a todos los valores de una columna, recordemos que también se imprimira su `index`.

In [12]:
print(paises.poblacion)

### También esto funciona
print("\n", paises["poblacion"])

China             1439.0
India             1380.0
Estados Unidos     331.0
Indonesia          273.0
Paskitán           220.0
Brasil             212.0
Nigeria            206.0
Bangladesh         164.0
Rusia              145.0
México             128.0
Name: poblacion, dtype: float64

 China             1439.0
India             1380.0
Estados Unidos     331.0
Indonesia          273.0
Paskitán           220.0
Brasil             212.0
Nigeria            206.0
Bangladesh         164.0
Rusia              145.0
México             128.0
Name: poblacion, dtype: float64

In [13]:
### También podríamos imprimer una serie de columnas que nosotros queramos
paises[["poblacion", "porcentaje"]]

                poblacion  porcentaje
China              1439.0       18.47
India              1380.0       17.70
Estados Unidos      331.0        4.25
Indonesia           273.0        3.51
Paskitán            220.0        2.83
Brasil              212.0        2.73
Nigeria             206.0        2.64
Bangladesh          164.0        2.11
Rusia               145.0        1.87
México              128.0        1.65

* ***NOTA***
  - `iloc` signicia `i` de entero y `loc` para la locación.
  - También podieramos usar `paises.loc["China"]`.
  - Por nuevas versiones de pandas, debemos usar para que no marque error
```python
paises["poblacion"].iloc[1] 
paises.poblacion[0] # también marca error
paises.poblacion.iloc[0] # así ya no
```

In [15]:
### Así accedemos a un elmento espefico, aunque esto ya no es correcto
paises["poblacion"][1]

C:\Users\PC\AppData\Local\Temp\ipykernel_20212\2363469948.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  paises["poblacion"][1]

1380.0

In [16]:
paises["poblacion"][0:3]

China             1439.0
India             1380.0
Estados Unidos     331.0
Name: poblacion, dtype: float64

## Métodos básicos comunes de DataFrames

In [17]:
### Así cambiamos el tipo de dato de una columna
paises["poblacion"] = paises["poblacion"].astype("int")

In [18]:
### Así mostramos la descripción de la tabla
### Podemos ver como ya cambió el tipo de dato a int32
paises.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, China to México
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   poblacion   10 non-null     int32
 1   porcentaje  10 non-null     float64
dtypes: float64(1), int32(1)
memory usage: 500.0+ bytes

In [19]:
### traernos los primeros 5 y los ultimos 5 por default, aunque también podemos especificar
paises.head(3), paises.tail(2)

(                poblacion  porcentaje
 China                1439       18.47
 India                1380       17.70
 Estados Unidos        331        4.25,
         poblacion  porcentaje
 Rusia         145        1.87
 México        128        1.65)

* `paises.sort_values(by=["poblacion"], ascending=False, inplace=True)`, necesario para que se guarde.
* `ascending=True`: menor a mayor en ese orden.

In [23]:
### Podemos ordenar, pero aquí tenemos que espeficar, creo que toma de menor a mayor por default
print("Paises: \n", paises)
ordenados = paises.sort_values(by=["poblacion"], ascending=True)
print("Paises Ordenados: \n", ordenados)

Paises:
                 poblacion  porcentaje
China                1439       18.47
India                1380       17.70
Estados Unidos        331        4.25
Indonesia             273        3.51
Paskitán              220        2.83
Brasil                212        2.73
Nigeria               206        2.64
Bangladesh            164        2.11
Rusia                 145        1.87
México                128        1.65
Paises Ordenados:
                 poblacion  porcentaje
México                128        1.65
Rusia                 145        1.87
Bangladesh            164        2.11
Nigeria               206        2.64
Brasil                212        2.73
Paskitán              220        2.83
Indonesia             273        3.51
Estados Unidos        331        4.25
India                1380       17.70
China                1439       18.47

In [24]:
# Si no nos interesara esto, podriamos ordenar por nuestro index
# es este caso los ordenara por orden alfabetico
paises.sort_index()

                poblacion  porcentaje
Bangladesh            164        2.11
Brasil                212        2.73
China                1439       18.47
Estados Unidos        331        4.25
India                1380       17.70
Indonesia             273        3.51
México                128        1.65
Nigeria               206        2.64
Paskitán              220        2.83
Rusia                 145        1.87

## Agregar y borrar Renglones y Columnas

In [29]:
### tasa defertilidad por pais
tasa_fertalidad = [1.7, 2.2, 1.8, 2.3, 3.6, 1.7, 5.4, 2.1, 1.8, 2.1]

# Agregariamos estos valores como si se tratara de un diccionario
paises["tasa_fertalidad"] = tasa_fertalidad
paises

                poblacion  porcentaje  tasa_fertalidad
China                1439       18.47              1.7
India                1380       17.70              2.2
Estados Unidos        331        4.25              1.8
Indonesia             273        3.51              2.3
Paskitán              220        2.83              3.6
Brasil                212        2.73              1.7
Nigeria               206        2.64              5.4
Bangladesh            164        2.11              2.1
Rusia                 145        1.87              1.8
México                128        1.65              2.1

* Al hacer ` paises.pop("poblacion")` nos regresa la columna.
* `del` sí modifica el DataFrame directamente.
* No necesita `inplace=True` porque no es un método de pandas, es una palabra reservada de Python.
* Por ultimo `.drop()`, este borra como tazas y columnas, `axis=1` es una columna, `axis=0` es un renglon.
* Por si solo, no la modifica, tenemos que activar que la modifica
* ***¿Cuándo usar cada uno?***
  - `del` → cuando solo quieres borrar y no necesitas la columna.
  - `pop()` → cuando quieres borrar y además guardar la columna.
  - `drop()` → cuando quieres más control (varias columnas, filas, etc.).

In [26]:
### Así podemos eliminar una columna, y te muestra la columna que borro
paises.pop("tasa_fertalidad")

China             1.7
India             2.2
Estados Unidos    1.8
Indonesia         2.3
Paskitán          3.6
Brasil            1.7
Nigeria           5.4
Bangladesh        2.1
Rusia             1.8
México            2.1
Name: tasa_fertalidad, dtype: float64

In [55]:
### hace un borrado pero no muestra lo que borro como el anterior
del paises["tasa_fertalidad"]

In [27]:
paises

                poblacion  porcentaje
China                1439       18.47
India                1380       17.70
Estados Unidos        331        4.25
Indonesia             273        3.51
Paskitán              220        2.83
Brasil                212        2.73
Nigeria               206        2.64
Bangladesh            164        2.11
Rusia                 145        1.87
México                128        1.65

In [30]:
paises.drop("tasa_fertalidad", axis=1, inplace=True)

In [31]:
### Agregar un valor, como los data frames están hechos de series, tenemos que dar de alta una
renglon = pd.Series(name="Japón", data=[126,1.62], index=["poblacion", "porcentaje"])
print("Nueva data :\n", renglon)
#paises.append(renglon) # esto ya esta desactualizado

### Aquí convertimos la serie a dataframe de una fila, y lo concatemos con paises
### Hay que transponerla para que tenga forma horizontal como una fila de excel
paises = pd.concat([paises, renglon.to_frame().T])
paises

Nueva data :
 poblacion     126.00
porcentaje      1.62
Name: Japón, dtype: float64

                poblacion  porcentaje
China              1439.0       18.47
India              1380.0       17.70
Estados Unidos      331.0        4.25
Indonesia           273.0        3.51
Paskitán            220.0        2.83
Brasil              212.0        2.73
Nigeria             206.0        2.64
Bangladesh          164.0        2.11
Rusia               145.0        1.87
México              128.0        1.65
Japón               126.0        1.62

In [32]:
### Ahora hagamos que borre varios datos por fila
paises.drop(["Japón", "Bangladesh"], axis = 0, inplace=True)

## Funciones de Estadísitica y de agregación básica

In [35]:
### igual que las series podemos pedir un pequeño resumen
print("Describe: \n", paises.describe())
print("\n Min: \n", paises.min())

Describe:
          poblacion  porcentaje
count     9.000000    9.000000
mean    481.555556    6.183333
std     529.780405    6.794868
min     128.000000    1.650000
25%     206.000000    2.640000
50%     220.000000    2.830000
75%     331.000000    4.250000
max    1439.000000   18.470000

 Min:
 poblacion     128.00
porcentaje      1.65
dtype: float64

In [37]:
### podemos pedir acumulativos, se va sumando el porcentaje y la poblacion
paises.cumsum()

                poblacion  porcentaje
China              1439.0       18.47
India              2819.0       36.17
Estados Unidos     3150.0       40.42
Indonesia          3423.0       43.93
Paskitán           3643.0       46.76
Brasil             3855.0       49.49
Nigeria            4061.0       52.13
Rusia              4206.0       54.00
México             4334.0       55.65